-- MySQL Script generated by MySQL Workbench
-- Sat Oct 26 14:55:31 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema QuickChat
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema QuickChat
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `QuickChat` DEFAULT CHARACTER SET utf8 ;
USE `QuickChat` ;

-- -----------------------------------------------------
-- Table `QuickChat`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `QuickChat`.`Users` (
  `idUsers` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NULL DEFAULT NULL,
  `Age` INT NULL DEFAULT NULL,
  `Email` VARCHAR(45) NULL DEFAULT NULL,
  `PhoneNumber` VARCHAR(45) NULL DEFAULT NULL,
  `Infractions` INT NULL DEFAULT NULL,
  `Created` DATETIME NULL DEFAULT NOW(),
  PRIMARY KEY (`idUsers`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `QuickChat`.`UsersChatrooms`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `QuickChat`.`UsersChatrooms` (
  `idUsersChatrooms` INT NOT NULL AUTO_INCREMENT,
  `idChatrooms` INT NOT NULL,
  `idUsers` INT NOT NULL,
  PRIMARY KEY (`idUsersChatrooms`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `QuickChat`.`Chatrooms`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `QuickChat`.`Chatrooms` (
  `idChatrooms` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NULL DEFAULT NULL,
  `Created` DATETIME NULL DEFAULT NOW(),
  PRIMARY KEY (`idChatrooms`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `QuickChat`.`Messages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `QuickChat`.`Messages` (
  `idMessages` INT NOT NULL AUTO_INCREMENT,
  `idUsers` INT NULL DEFAULT NULL,
  `idChatrooms` INT NULL DEFAULT NULL,
  `Content` VARCHAR(255) NULL DEFAULT NULL,
  `Created` DATETIME NULL DEFAULT NOW(),
  PRIMARY KEY (`idMessages`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
